### ISSUE TITLE
Sniffer windows PcapTimeoutElapsed

### ISSUE THREAD

**Issue by samadouz** [louisabraham/LaBot#24]
Bonjour,

J'essaye de faire marcher le sniffer sous windows, quand je clique sur "Start" j'ai cette erreur là: 

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Abdessamad\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Abdessamad\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Abdessamad\Desktop\dofusprojects\LaBot\labot\sniffer\network.py", line 211, in _sniff
    prn=lambda p: on_receive(p, action),
  File "C:\Users\Abdessamad\Desktop\dofusprojects\LaBot\labot\sniffer\network.py", line 78, in sniff
    from scapy.arch.pcapdnet import PcapTimeoutElapsed
ImportError: cannot import name 'PcapTimeoutElapsed' from 'scapy.arch.pcapdnet' (C:\Users\Abdessamad\AppData\Local\Programs\Python\Python37\lib\site-packages\scapy\arch\pcapdnet.py)

PS : J'utilise Scapy 2.4.3

Merci d'avance

**Comment by samadouz** [comment]
If someone encounters this issue, go to pcapdnet.py and put this empty class as follows
class PcapTimeoutElapsed(Scapy_Exception):
      pass
