### ISSUE TITLE
Erreur " AssertionError "

### ISSUE THREAD

**Issue by pyloverm** [louisabraham/LaBot#29]
Bonjour,je ne sais si tu es encore actif sur ce projet mais je tente ma chance.

quand je lance le script apres avoir decompiler a l'aide du "decompile.sh" j'obtiens cette erreur.

`30%|█████████████████▏                                        | 434/1466 [00:00<00:01, 555.53it/s]
Traceback (most recent call last):
  File "C:\Users\#####\Desktop\DofusHelper-main\LaBot-master\scripts\build_protocol.py", line 196, in <module>
    build()
  File "C:\Users\#####\Desktop\DofusHelper-main\LaBot-master\scripts\build_protocol.py", line 168, in build
    parse(t)
  File "C:\Users\#####\Desktop\DofusHelper-main\LaBot-master\scripts\build_protocol.py", line 148, in parse
    assert protocolId not in msg_from_id
AssertionError`

**Comment by pyloverm** [comment]
rien
